# Fig pre block. Keep at the top of this file.
[ -f "$HOME/.fig/shell/zprofile.pre.zsh" ] && . "$HOME/.fig/shell/zprofile.pre.zsh"

DEFAULT_USER="teeseal"
EDITOR="vim"
VISUAL="code"
export LANG="en_GB.UTF-8"
export LC_ALL="en_US.UTF-8"

# Fig post block. Keep at the bottom of this file.
[ -f "$HOME/.fig/shell/zprofile.post.zsh" ] && . "$HOME/.fig/shell/zprofile.post.zsh"
