[ -f "/opt/homebrew/bin/brew" ] && eval "$(/opt/homebrew/bin/brew shellenv)"

export DOTFILES="$HOME/.dotfiles"
export ZI_HOME="$HOME/.zi"

# Plugins
source "$ZI_HOME/bin/zi.zsh"
autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi

zi wait lucid light-mode for \
  multisrc="*" "$DOTFILES/configs" \
  iridakos/goto \
  atload="_zsh_autosuggest_start" zsh-users/zsh-autosuggestions \
  if="which git >/dev/null 2>&1" OMZP::git \
  if="which bundler >/dev/null 2>&1" OMZP::bundler

zi light-mode for \
  mafredri/zsh-async \
  pick="async.zsh" src="pure.zsh" sindresorhus/pure \
  z-shell/F-Sy-H

# GPG
export GPG_TTY=$(tty)

# Colors
export CLICOLOR=1
export LSCOLORS="Gxfxcxdxbxegedabagacad"

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_SPACE

# asdf
[ -f "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh" ] && source "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"

# Source fzf if present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source localrc
[ -f "$HOME/.localrc" ] && source "$HOME/.localrc"

# Source secretrc
[ -f "$HOME/.secretrc" ] && source "$HOME/.secretrc"

# Make all PATH entires unique
typeset -aU path
