export DOTFILES="$HOME/.dotfiles"
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# GPG
export GPG_TTY=$(tty)

# Colors
export CLICOLOR=1
export LSCOLORS="Gxfxcxdxbxegedabagacad"

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY

# Configs
zplug "$DOTFILES", from:local, use:"configs/*"

# From Oh My Zsh
zplug plugins/git,     from:oh-my-zsh, if:"which git"
zplug plugins/bundler, from:oh-my-zsh, if:"which bundler"

zplug mafredri/zsh-async, use:async.zsh
zplug sindresorhus/pure, use:pure.zsh, as:theme
zplug zsh-users/zsh-autosuggestions
zplug zdharma/fast-syntax-highlighting

# Install missing plugins if needed
zplug check --verbose || zplug install

# Load plugins
zplug load

# Source fzf if present
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source localrc
[ -f "$HOME/.localrc" ] && source "$HOME/.localrc"

# Make all PATH entires unique
typeset -aU path
