#!/usr/bin/env sh

if which antibody >/dev/null 2>&1; then
  brew upgrade antibody
else
  brew install getantibody/tap/antibody
fi

antibody bundle <"$DOTFILES/antibody/plugins.txt" >~/.zsh_plugins.sh
antibody update
