code --install-extension JakeBecker.elixir-ls
code --install-extension PeterJausovec.vscode-docker
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbankier.vscode-quick-select
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension mikestead.dotenv
code --install-extension rebornix.Ruby
code --install-extension robertohuertasm.vscode-icons
code --install-extension steve8708.Align
code --install-extension teabyii.ayu
