#!/usr/bin/env zsh

printf "Install Visual Studio Code? [y/n]: "
read -q || exit 0
echo

which code >/dev/null 2>&1 || brew cask install visual-studio-code

VSCODE_USER="$HOME/Library/Application Support/Code/User"

ln -sf "$DOTFILES/vscode/settings.json" "$VSCODE_USER/settings.json"
ln -sf "$DOTFILES/vscode/keybindings.json" "$VSCODE_USER/keybindings.json"
ln -sf "$DOTFILES/vscode/snippets" "$VSCODE_USER/snippets"

echo "✅  linked config files"
echo "🚚  installing extensions"

for ext in $(cat "$DOTFILES/vscode/extensions.txt"); do
  code --install-extension "$ext" || true
done
