#!/usr/bin/env zsh

echo ''
echo "🔗  SYMLINKS"

link_file() {
  if [ -e "$2" ]; then
    if [ "$1" -ef "$2" ]; then
      echo "✅  $1 already linked"
      return 0
    else
      mv "$2" "$2.bak"
      echo "⚠️  moved $2 to $2.bak"
    fi
  fi

  ln -sf "$1" "$2"
  echo "✅  linked $1 to $2"
}

for src in $(find -H "$DOTFILES" -name '*.symlink'); do
  dest="$HOME/.$(basename "${src%.*}")"
  link_file "$src" "$dest"
done
